[audio_wav,fs_wav] = audioread("/home/paso/Documents/Aclai/Audio911.jl/test/test_files/test.wav");

aFE = audioFeatureExtractor( ...
    SampleRate=fs_wav, ...
    Window=hamming(512,"periodic"), ...
    OverlapLength=256, ...
    barkSpectrum=true);
setExtractorParameters(aFE,"barkSpectrum",FrequencyRange=[100,1000], ... 
    SpectrumType="power", NumBands=26, FilterBankNormalization="bandwidth", ...
    WindowNormalization=true, FilterBankDesignDomain="linear", ...
    ApplyLog=false)
features = extract(aFE, audio_wav);
save matlab_barkspec_01.mat features

aFE = audioFeatureExtractor( ...
    SampleRate=fs_wav, ...
    Window=hamming(512,"periodic"), ...
    OverlapLength=256, ...
    barkSpectrum=true);
setExtractorParameters(aFE,"barkSpectrum",FrequencyRange=[100,1000], ... 
    SpectrumType="magnitude", NumBands=26, FilterBankNormalization="bandwidth", ...
    WindowNormalization=true, FilterBankDesignDomain="linear", ...
    ApplyLog=false)
features = extract(aFE, audio_wav);
save matlab_barkspec_02.mat features

aFE = audioFeatureExtractor( ...
    SampleRate=fs_wav, ...
    Window=hamming(512,"periodic"), ...
    OverlapLength=256, ...
    barkSpectrum=true);
setExtractorParameters(aFE,"barkSpectrum",FrequencyRange=[100,1000], ... 
    SpectrumType="power", NumBands=26, FilterBankNormalization="bandwidth", ...
    WindowNormalization=true, FilterBankDesignDomain="linear", ...
    ApplyLog=false)
features = extract(aFE, audio_wav);
save matlab_barkspec_03.mat features

aFE = audioFeatureExtractor( ...
    SampleRate=fs_wav, ...
    Window=hamming(512,"periodic"), ...
    OverlapLength=256, ...
    barkSpectrum=true);
setExtractorParameters(aFE,"barkSpectrum",FrequencyRange=[100,1000], ... 
    SpectrumType="magnitude", NumBands=26, FilterBankNormalization="bandwidth", ...
    WindowNormalization=true, FilterBankDesignDomain="linear", ...
    ApplyLog=false)
features = extract(aFE, audio_wav);
save matlab_barkspec_04.mat features