[audio_wav,fs_wav] = audioread("/home/paso/Documents/Aclai/Audio911.jl/test/test_files/test.wav");

aFE = audioFeatureExtractor( ...
    SampleRate=fs_wav, ...
    Window=hamming(512,"periodic"), ...
    OverlapLength=256, ...
    gtcc=true);
setExtractorParameters(aFE,"gtcc", NumCoeffs=13, Rectification="log");
features = extract(aFE, audio_wav);
save matlab_gtcc_01.mat features

aFE = audioFeatureExtractor( ...
    SampleRate=fs_wav, ...
    Window=hamming(512,"periodic"), ...
    OverlapLength=256, ...
    gtcc=true);
setExtractorParameters(aFE,"gtcc", NumCoeffs=30, Rectification="cubic-root");
features = extract(aFE, audio_wav);
save matlab_gtcc_02.mat features
