[audio_wav,fs_wav] = audioread("/home/paso/Documents/Aclai/PasoStudio73/Audio911.jl/test/test_files/test.wav");

aFE = audioFeatureExtractor( ...
    SampleRate=fs_wav, ...
    Window=hamming(512,"periodic"), ...
    OverlapLength=256, ...
    melSpectrum=true);
setExtractorParameters(aFE,"melSpectrum",FrequencyRange=[100,1000], ... 
    SpectrumType="power", NumBands=26, FilterBankNormalization="bandwidth", ...
    WindowNormalization=true, FilterBankDesignDomain="linear", ...
    MelStyle="oshaughnessy", ApplyLog=false)
features = extract(aFE, audio_wav);
save matlab_melspec_01.mat features

aFE = audioFeatureExtractor( ...
    SampleRate=fs_wav, ...
    Window=hamming(512,"periodic"), ...
    OverlapLength=256, ...
    melSpectrum=true);
setExtractorParameters(aFE,"melSpectrum",FrequencyRange=[100,1000], ... 
    SpectrumType="magnitude", NumBands=26, FilterBankNormalization="bandwidth", ...
    WindowNormalization=true, FilterBankDesignDomain="linear", ...
    MelStyle="oshaughnessy", ApplyLog=false)
features = extract(aFE, audio_wav);
save matlab_melspec_02.mat features

aFE = audioFeatureExtractor( ...
    SampleRate=fs_wav, ...
    Window=hamming(512,"periodic"), ...
    OverlapLength=256, ...
    melSpectrum=true);
setExtractorParameters(aFE,"melSpectrum",FrequencyRange=[100,1000], ... 
    SpectrumType="power", NumBands=26, FilterBankNormalization="bandwidth", ...
    WindowNormalization=false, FilterBankDesignDomain="linear", ...
    MelStyle="oshaughnessy", ApplyLog=false)
features = extract(aFE, audio_wav);
save matlab_melspec_03.mat features

aFE = audioFeatureExtractor( ...
    SampleRate=fs_wav, ...
    Window=hamming(512,"periodic"), ...
    OverlapLength=256, ...
    melSpectrum=true);
setExtractorParameters(aFE,"melSpectrum",FrequencyRange=[100,1000], ... 
    SpectrumType="magnitude", NumBands=26, FilterBankNormalization="bandwidth", ...
    WindowNormalization=false, FilterBankDesignDomain="linear", ...
    MelStyle="oshaughnessy", ApplyLog=false)
features = extract(aFE, audio_wav);
save matlab_melspec_04.mat features