[audio_wav,fs_wav] = audioread("/home/paso/Documents/Aclai/Audio911.jl/test/test_files/test.wav");

% aFE = audioFeatureExtractor( ...
%     SampleRate=fs_wav, ...
%     Window=hamming(512,"periodic"), ...
%     OverlapLength=256, ...
%     mfcc=true);
% setExtractorParameters(aFE,"mfcc", NumCoeffs=13, Rectification="log");
% features = extract(aFE, audio_wav);
% save matlab_mfcc_01.mat features

% aFE = audioFeatureExtractor( ...
%     SampleRate=fs_wav, ...
%     Window=hamming(512,"periodic"), ...
%     OverlapLength=256, ...
%     mfcc=true);
% setExtractorParameters(aFE,"mfcc", NumCoeffs=30, Rectification="cubic-root");
% features = extract(aFE, audio_wav);
% save matlab_mfcc_02.mat features

% aFE = audioFeatureExtractor( ...
%     SampleRate=fs_wav, ...
%     Window=hamming(512,"periodic"), ...
%     OverlapLength=256, ...
%     mfccDelta=true);
% setExtractorParameters(aFE,"mfcc", NumCoeffs=13, Rectification="log");
% features = extract(aFE, audio_wav);
% save matlab_delta.mat features
% 
% aFE = audioFeatureExtractor( ...
%     SampleRate=fs_wav, ...
%     Window=hamming(512,"periodic"), ...
%     OverlapLength=256, ...
%     mfccDeltaDelta=true);
% setExtractorParameters(aFE,"mfcc", NumCoeffs=13, Rectification="log");
% features = extract(aFE, audio_wav);
% save matlab_deltadelta.mat features