[audio_wav,fs_wav] = audioread("/home/paso/Documents/Aclai/Audio911.jl/test/test_files/test.wav");

% aFE = audioFeatureExtractor( ...
%     SampleRate=fs_wav, ...
%     Window=hamming(512,"periodic"), ...
%     OverlapLength=256, ...
%     spectralCentroid=true);
% setExtractorParameters(aFE,"linearSpectrum",FrequencyRange=[100,1000], SpectrumType="power", WindowNormalization=true)
% features = extract(aFE, audio_wav);
% save matlab_spectralCentroid.mat features

% aFE = audioFeatureExtractor( ...
%     SampleRate=fs_wav, ...
%     Window=hamming(512,"periodic"), ...
%     OverlapLength=256, ...
%     spectralCrest=true);
% setExtractorParameters(aFE,"linearSpectrum",FrequencyRange=[100,1000], SpectrumType="power", WindowNormalization=true)
% features = extract(aFE, audio_wav);
% save matlab_spectralCrest.mat features

% aFE = audioFeatureExtractor( ...
%     SampleRate=fs_wav, ...
%     Window=hamming(512,"periodic"), ...
%     OverlapLength=256, ...
%     spectralDecrease=true);
% setExtractorParameters(aFE,"linearSpectrum",FrequencyRange=[100,1000], SpectrumType="power", WindowNormalization=true)
% features = extract(aFE, audio_wav);
% save matlab_spectralDecrease.mat features

% aFE = audioFeatureExtractor( ...
%     SampleRate=fs_wav, ...
%     Window=hamming(512,"periodic"), ...
%     OverlapLength=256, ...
%     spectralEntropy=true);
% setExtractorParameters(aFE,"linearSpectrum",FrequencyRange=[100,1000], SpectrumType="power", WindowNormalization=true)
% features = extract(aFE, audio_wav);
% save matlab_spectralEntropy.mat features

% aFE = audioFeatureExtractor( ...
%     SampleRate=fs_wav, ...
%     Window=hamming(512,"periodic"), ...
%     OverlapLength=256, ...
%     spectralFlatness=true);
% setExtractorParameters(aFE,"linearSpectrum",FrequencyRange=[100,1000], SpectrumType="power", WindowNormalization=true)
% features = extract(aFE, audio_wav);
% save matlab_spectralFlatness.mat features

% aFE = audioFeatureExtractor( ...
%     SampleRate=fs_wav, ...
%     Window=hamming(512,"periodic"), ...
%     OverlapLength=256, ...
%     spectralFlux=true);
% setExtractorParameters(aFE,"linearSpectrum",FrequencyRange=[100,1000], SpectrumType="power", WindowNormalization=true)
% setExtractorParameters(aFE,"spectralFlux",  NormType=1)
% features = extract(aFE, audio_wav);
% save matlab_spectralFlux1.mat features

% aFE = audioFeatureExtractor( ...
%     SampleRate=fs_wav, ...
%     Window=hamming(512,"periodic"), ...
%     OverlapLength=256, ...
%     spectralFlux=true);
% setExtractorParameters(aFE,"linearSpectrum",FrequencyRange=[100,1000], SpectrumType="power", WindowNormalization=true)
% setExtractorParameters(aFE,"spectralFlux",  NormType=2)
% features = extract(aFE, audio_wav);
% save matlab_spectralFlux2.mat features

aFE = audioFeatureExtractor( ...
    SampleRate=fs_wav, ...
    Window=hamming(512,"periodic"), ...
    OverlapLength=256, ...
    spectralKurtosis=true);
setExtractorParameters(aFE,"linearSpectrum",FrequencyRange=[100,1000], SpectrumType="power", WindowNormalization=true)
features = extract(aFE, audio_wav);
save matlab_spectralKurtosis.mat features

aFE = audioFeatureExtractor( ...
    SampleRate=fs_wav, ...
    Window=hamming(512,"periodic"), ...
    OverlapLength=256, ...
    spectralRolloffPoint=true);
setExtractorParameters(aFE,"linearSpectrum",FrequencyRange=[100,1000], SpectrumType="power", WindowNormalization=true)
setExtractorParameters(aFE,"spectralRolloffPoint", Threshold=0.95)
features = extract(aFE, audio_wav);
save matlab_spectralRolloff95.mat features

aFE = audioFeatureExtractor( ...
    SampleRate=fs_wav, ...
    Window=hamming(512,"periodic"), ...
    OverlapLength=256, ...
    spectralRolloffPoint=true);
setExtractorParameters(aFE,"linearSpectrum",FrequencyRange=[100,1000], SpectrumType="power", WindowNormalization=true)
setExtractorParameters(aFE,"spectralRolloffPoint", Threshold=0.65)
features = extract(aFE, audio_wav);
save matlab_spectralRolloff65.mat features

aFE = audioFeatureExtractor( ...
    SampleRate=fs_wav, ...
    Window=hamming(512,"periodic"), ...
    OverlapLength=256, ...
    spectralSkewness=true);
setExtractorParameters(aFE,"linearSpectrum",FrequencyRange=[100,1000], SpectrumType="power", WindowNormalization=true)
features = extract(aFE, audio_wav);
save matlab_spectralSkewness.mat features

aFE = audioFeatureExtractor( ...
    SampleRate=fs_wav, ...
    Window=hamming(512,"periodic"), ...
    OverlapLength=256, ...
    spectralSlope=true);
setExtractorParameters(aFE,"linearSpectrum",FrequencyRange=[100,1000], SpectrumType="power", WindowNormalization=true)
features = extract(aFE, audio_wav);
save matlab_spectralSlope.mat features

aFE = audioFeatureExtractor( ...
    SampleRate=fs_wav, ...
    Window=hamming(512,"periodic"), ...
    OverlapLength=256, ...
    spectralSpread=true);
setExtractorParameters(aFE,"linearSpectrum",FrequencyRange=[100,1000], SpectrumType="power", WindowNormalization=true)
features = extract(aFE, audio_wav);
save matlab_spectralSpread.mat features
